# Inspect source files (data catalog)

This notebook loads the inventory produced by `src/catalog/build_data_catalog.py` and explores what lives under `data/raw/`.

**Tip:** Run Jupyter with the **project root** as the working directory (the folder that contains `outputs/` and `data/`). The code below searches upward from the current folder until it finds `outputs/tables/data_catalog.csv`.

## 1. Load the catalog CSV

We use **pandas** `read_csv` to read the table into a **DataFrame** (`df`). Each row is one file discovered under `data/raw/`.

In [17]:
from pathlib import Path

import pandas as pd


def find_project_root() -> Path:
    """Walk up from cwd until we find the catalog CSV (works from project root or notebooks/)."""
    here = Path.cwd().resolve()
    for folder in [here, *here.parents]:
        catalog = folder / "outputs" / "tables" / "data_catalog.csv"
        if catalog.is_file():
            return folder
    raise FileNotFoundError(
        "Could not find outputs/tables/data_catalog.csv. "
        "Open the project folder as Jupyter's root or run: cd <project-root>"
    )


ROOT = find_project_root()
catalog_path = ROOT / "outputs" / "tables" / "data_catalog.csv"

df = pd.read_csv(catalog_path)
print(f"Loaded {len(df)} rows from {catalog_path}")

Loaded 91 rows from /Users/iagolarrondo/Library/CloudStorage/OneDrive-MassachusettsInstituteofTechnology/1. Coursework and academic/Y2 ('25-'26) - IAP, H3 & H4/15.S04 – Gen AI Lab/2. Assignments and deliverables/Manulife Project/outputs/tables/data_catalog.csv

## 2. Display the full catalog

Show every row. We temporarily raise pandas’ row limit so nothing is hidden (your catalog is small enough for this).

In [18]:
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.width", None):
    display(df)

,relative_path,file_name,extension,top_level_group
0,.DS_Store,.DS_Store,NaN,other
1,ddl/.gitkeep,.gitkeep,NaN,ddl
2,ddl/Create_Table__INVESTIGAI_ICP_CAREGIVER_APP...,Create_Table__INVESTIGAI_ICP_CAREGIVER_APP_SES...,.sql,ddl
3,ddl/Create_Table__INVESTIGAI_ICP_WORK_BLOCKS.sql,Create_Table__INVESTIGAI_ICP_WORK_BLOCKS.sql,.sql,ddl
4,ddl/Create_Table__INVESTIGAI_PROVIDER_CLAIMS.sql,Create_Table__INVESTIGAI_PROVIDER_CLAIMS.sql,.sql,ddl
5,ddl/Create_Table__T_NORM_CARE_SESSION.sql,Create_Table__T_NORM_CARE_SESSION.sql,.sql,ddl
6,ddl/Create_Table__T_NORM_CARE_SESSION_EVENT.sql,Create_Table__T_NORM_CARE_SESSION_EVENT.sql,.sql,ddl
7,ddl/Create_Table__T_NORM_CHARGE.sql,Create_Table__T_NORM_CHARGE.sql,.sql,ddl
8,ddl/Create_Table__T_NORM_CLAIM.sql,Create_Table__T_NORM_CLAIM.sql,.sql,ddl
9,ddl/Create_Table__T_NORM_CLAIM_ELIGIBILITY_REV...,Create_Table__T_NORM_CLAIM_ELIGIBILITY_REVIEW_...,.sql,ddl
10,ddl/Create_Table__T_NORM_CLINICAL_REVIEW.sql,Create_Table__T_NORM_CLINICAL_REVIEW.sql,.sql,ddl
11,ddl/Create_Table__T_NORM_DIAGNOSIS.sql,Create_Table__T_NORM_DIAGNOSIS.sql,.sql,ddl
12,ddl/Create_Table__T_NORM_ELIGIBILITY_REVIEW.sql,Create_Table__T_NORM_ELIGIBILITY_REVIEW.sql,.sql,ddl
13,ddl/Create_Table__T_NORM_INVOICE.sql,Create_Table__T_NORM_INVOICE.sql,.sql,ddl
14,ddl/Create_Table__T_NORM_PAYMENT.sql,Create_Table__T_NORM_PAYMENT.sql,.sql,ddl
15,ddl/Create_Table__T_NORM_POLICY.sql,Create_Table__T_NORM_POLICY.sql,.sql,ddl
16,ddl/Create_Table__T_NORM_POLICY_RIDER.sql,Create_Table__T_NORM_POLICY_RIDER.sql,.sql,ddl
17,ddl/Create_Table__T_NORM_REVIEW_CYCLE.sql,Create_Table__T_NORM_REVIEW_CYCLE.sql,.sql,ddl
18,ddl/Create_Table__T_NORM_REVIEW_CYCLE_METRIC.sql,Create_Table__T_NORM_REVIEW_CYCLE_METRIC.sql,.sql,ddl
19,ddl/Create_Table__T_NORM_REVIEW_CYCLE_REMEDIAT...,Create_Table__T_NORM_REVIEW_CYCLE_REMEDIATION.sql,.sql,ddl
20,ddl/Create_Table__T_RESOLVED_ADDRESS.sql,Create_Table__T_RESOLVED_ADDRESS.sql,.sql,ddl
21,ddl/Create_Table__T_RESOLVED_BANK_ACCOUNT.sql,Create_Table__T_RESOLVED_BANK_ACCOUNT.sql,.sql,ddl
22,ddl/Create_Table__T_RESOLVED_BUSINESS.sql,Create_Table__T_RESOLVED_BUSINESS.sql,.sql,ddl
23,ddl/Create_Table__T_RESOLVED_BUSINESS_ADDRESS_...,Create_Table__T_RESOLVED_BUSINESS_ADDRESS_CROS...,.sql,ddl
24,ddl/Create_Table__T_RESOLVED_BUSINESS_ELIGIBIL...,Create_Table__T_RESOLVED_BUSINESS_ELIGIBILITY_...,.sql,ddl
25,ddl/Create_Table__T_RESOLVED_BUSINESS_INVOICE_...,Create_Table__T_RESOLVED_BUSINESS_INVOICE_CROS...,.sql,ddl
26,ddl/Create_Table__T_RESOLVED_BUSINESS_PERSON_C...,Create_Table__T_RESOLVED_BUSINESS_PERSON_CROSS...,.sql,ddl
27,ddl/Create_Table__T_RESOLVED_CARE_SESSION_EVEN...,Create_Table__T_RESOLVED_CARE_SESSION_EVENT_GE...,.sql,ddl
28,ddl/Create_Table__T_RESOLVED_CARE_SESSION_GEOL...,Create_Table__T_RESOLVED_CARE_SESSION_GEOLOCAT...,.sql,ddl
29,ddl/Create_Table__T_RESOLVED_GEOLOCATION.sql,Create_Table__T_RESOLVED_GEOLOCATION.sql,.sql,ddl
30,ddl/Create_Table__T_RESOLVED_PAYMENT_BANK_ACCO...,Create_Table__T_RESOLVED_PAYMENT_BANK_ACCOUNT_...,.sql,ddl
31,ddl/Create_Table__T_RESOLVED_PERSON.sql,Create_Table__T_RESOLVED_PERSON.sql,.sql,ddl
32,ddl/Create_Table__T_RESOLVED_PERSON_ADDRESS_CR...,Create_Table__T_RESOLVED_PERSON_ADDRESS_CROSSW...,.sql,ddl
33,ddl/Create_Table__T_RESOLVED_PERSON_BANK_ACCOU...,Create_Table__T_RESOLVED_PERSON_BANK_ACCOUNT_C...,.sql,ddl
34,ddl/Create_Table__T_RESOLVED_PERSON_CARE_SESSI...,Create_Table__T_RESOLVED_PERSON_CARE_SESSION_C...,.sql,ddl
35,ddl/Create_Table__T_RESOLVED_PERSON_ELIGIBILIT...,Create_Table__T_RESOLVED_PERSON_ELIGIBILITY_RE...,.sql,ddl
36,ddl/Create_Table__T_RESOLVED_PERSON_INVOICE_CR...,Create_Table__T_RESOLVED_PERSON_INVOICE_CROSSW...,.sql,ddl
37,ddl/Create_Table__T_RESOLVED_PERSON_PERSON_CRO...,Create_Table__T_RESOLVED_PERSON_PERSON_CROSSWA...,.sql,ddl
38,ddl/Create_Table__T_RESOLVED_PERSON_POLICY_CRO...,Create_Table__T_RESOLVED_PERSON_POLICY_CROSSWA...,.sql,ddl
39,ddl/Create_View__V_RESOLVED_CARE_SESSION_GEOLO...,Create_View__V_RESOLVED_CARE_SESSION_GEOLOCATI...,.sql,ddl
40,documentation/.gitkeep,.gitkeep,NaN,documentation
41,documentation/docs__COG_impairment.txt,docs__COG_impairment.txt,.txt,documentation
42,documentation/docs__DMB.txt,docs__DMB.txt,.txt,documentation
43,documentation/docs__HIPAA.txt,docs__HIPAA.txt,.txt,documentation
44,documentation/docs__INVESTIGAI_ICP_CAREGIVER_A...,docs__INVESTIGAI_ICP_CAREGIVER_APP_SESSIONS.txt,.txt,documentation
45,documentation/docs__POA.txt,docs__POA.txt,.txt,documentation
46,documentation/docs__T_NORM_CARE_SESSION.txt,docs__T_NORM_CARE_SESSION.txt,.txt,documentation
47,documentation/docs__T_NORM_CARE_SESSION_EVENT.txt,docs__T_NORM_CARE_SESSION_EVENT.txt,.txt,documentation
48,documentation/docs__T_NORM_CLAIM.txt,docs__T_NORM_CLAIM.txt,.txt,documentation
49,documentation/docs__T_NORM_CLAIM_ELIGIBILITY_R...,docs__T_NORM_CLAIM_ELIGIBILITY_REVIEW_CROSSWAL...,.txt,documentation
50,documentation/docs__T_NORM_CLINICAL_REVIEW.txt,docs__T_NORM_CLINICAL_REVIEW.txt,.txt,documentation
51,documentation/docs__T_NORM_DIAGNOSIS.txt,docs__T_NORM_DIAGNOSIS.txt,.txt,documentation
52,documentation/docs__T_NORM_ELIGIBILITY_REVIEW.txt,docs__T_NORM_ELIGIBILITY_REVIEW.txt,.txt,documentation
53,documentation/docs__T_NORM_INVOICE.txt,docs__T_NORM_INVOICE.txt,.txt,documentation
54,documentation/docs__T_NORM_POLICY.txt,docs__T_NORM_POLICY.txt,.txt,documentation
55,documentation/docs__T_RESOLVED_ADDRESS.txt,docs__T_RESOLVED_ADDRESS.txt,.txt,documentation
56,documentation/docs__T_RESOLVED_BUSINESS.txt,docs__T_RESOLVED_BUSINESS.txt,.txt,documentation
57,documentation/docs__T_RESOLVED_BUSINESS_ELIGIB...,docs__T_RESOLVED_BUSINESS_ELIGIBILITY_REVIEW_C...,.txt,documentation
58,documentation/docs__T_RESOLVED_BUSINESS_INVOIC...,docs__T_RESOLVED_BUSINESS_INVOICE_CROSSWALK.txt,.txt,documentation
59,documentation/docs__T_RESOLVED_BUSINESS_PERSON...,docs__T_RESOLVED_BUSINESS_PERSON_CROSSWALK.txt,.txt,documentation
60,documentation/docs__T_RESOLVED_CARE_SESSION_GE...,docs__T_RESOLVED_CARE_SESSION_GEOLOCATION_CROS...,.txt,documentation
61,documentation/docs__T_RESOLVED_GEOLOCATION.txt,docs__T_RESOLVED_GEOLOCATION.txt,.txt,documentation
62,documentation/docs__T_RESOLVED_PERSON.txt,docs__T_RESOLVED_PERSON.txt,.txt,documentation
63,documentation/docs__T_RESOLVED_PERSON_ADDRESS_...,docs__T_RESOLVED_PERSON_ADDRESS_CROSSWALK.txt,.txt,documentation
64,documentation/docs__T_RESOLVED_PERSON_CARE_SES...,docs__T_RESOLVED_PERSON_CARE_SESSION_CROSSWALK...,.txt,documentation
65,documentation/docs__T_RESOLVED_PERSON_ELIGIBIL...,docs__T_RESOLVED_PERSON_ELIGIBILITY_REVIEW_CRO...,.txt,documentation
66,documentation/docs__T_RESOLVED_PERSON_INVOICE_...,docs__T_RESOLVED_PERSON_INVOICE_CROSSWALK.txt,.txt,documentation
67,documentation/docs__T_RESOLVED_PERSON_PERSON_C...,docs__T_RESOLVED_PERSON_PERSON_CROSSWALK.txt,.txt,documentation
68,documentation/docs__T_RESOLVED_PERSON_POLICY_C...,docs__T_RESOLVED_PERSON_POLICY_CROSSWALK.txt,.txt,documentation
69,documentation/docs__care_session_listings.txt,docs__care_session_listings.txt,.txt,documentation
70,documentation/docs__clinical_review_listings.txt,docs__clinical_review_listings.txt,.txt,documentation
71,documentation/docs__deceased.txt,docs__deceased.txt,.txt,documentation
72,documentation/docs__eligibility_review_query.txt,docs__eligibility_review_query.txt,.txt,documentation
73,documentation/docs__geolocation_enabled.txt,docs__geolocation_enabled.txt,.txt,documentation
74,documentation/docs__hourly_rate.txt,docs__hourly_rate.txt,.txt,documentation
75,documentation/docs__icp_no_breaks.txt,docs__icp_no_breaks.txt,.txt,documentation
76,documentation/docs__icp_shared_device_ids.txt,docs__icp_shared_device_ids.txt,.txt,documentation
77,documentation/docs__invoice_listings.txt,docs__invoice_listings.txt,.txt,documentation
78,documentation/docs__multi_icp_overlap.txt,docs__multi_icp_overlap.txt,.txt,documentation
79,documentation/docs__no_touch.txt,docs__no_touch.txt,.txt,documentation
80,documentation/docs__payments.txt,docs__payments.txt,.txt,documentation
81,documentation/docs__policyholder_query.txt,docs__policyholder_query.txt,.txt,documentation
82,documentation/docs__provider_query.txt,docs__provider_query.txt,.txt,documentation
83,documentation/docs__review_cycles.txt,docs__review_cycles.txt,.txt,documentation
84,documentation/docs__session_address_distance.txt,docs__session_address_distance.txt,.txt,documentation
85,documentation/docs__spouses.txt,docs__spouses.txt,.txt,documentation
86,documentation/docs__start_of_care.txt,docs__start_of_care.txt,.txt,documentation
87,documentation/docs__writing_agent.txt,docs__writing_agent.txt,.txt,documentation
88,graph/.gitkeep,.gitkeep,NaN,graph
89,graph/GRAPH_DATA_MODEL.md,GRAPH_DATA_MODEL.md,.md,graph
90,readme.md,readme.md,.md,other

## 3. File counts by `top_level_group`

`top_level_group` comes from the first folder under `data/raw/` (`ddl`, `documentation`, `graph`) or `other` for files sitting directly in `raw/` (and anything else unexpected).

In [19]:
counts = df["top_level_group"].value_counts().sort_index()
display(counts)

top_level_group
ddl              39
documentation    48
graph             2
other             2
Name: count, dtype: int64

## 4. All `.sql` files (DDL)

Filter rows where the **extension** column is `.sql`. These are the Snowflake-style table/view scripts under `data/raw/ddl/`.

In [20]:
sql_files = df[df["extension"] == ".sql"].copy()
sql_files = sql_files.sort_values("relative_path")
display(sql_files[["relative_path", "file_name", "top_level_group"]])

,relative_path,file_name,top_level_group
2,ddl/Create_Table__INVESTIGAI_ICP_CAREGIVER_APP...,Create_Table__INVESTIGAI_ICP_CAREGIVER_APP_SES...,ddl
3,ddl/Create_Table__INVESTIGAI_ICP_WORK_BLOCKS.sql,Create_Table__INVESTIGAI_ICP_WORK_BLOCKS.sql,ddl
4,ddl/Create_Table__INVESTIGAI_PROVIDER_CLAIMS.sql,Create_Table__INVESTIGAI_PROVIDER_CLAIMS.sql,ddl
5,ddl/Create_Table__T_NORM_CARE_SESSION.sql,Create_Table__T_NORM_CARE_SESSION.sql,ddl
6,ddl/Create_Table__T_NORM_CARE_SESSION_EVENT.sql,Create_Table__T_NORM_CARE_SESSION_EVENT.sql,ddl
7,ddl/Create_Table__T_NORM_CHARGE.sql,Create_Table__T_NORM_CHARGE.sql,ddl
8,ddl/Create_Table__T_NORM_CLAIM.sql,Create_Table__T_NORM_CLAIM.sql,ddl
9,ddl/Create_Table__T_NORM_CLAIM_ELIGIBILITY_REV...,Create_Table__T_NORM_CLAIM_ELIGIBILITY_REVIEW_...,ddl
10,ddl/Create_Table__T_NORM_CLINICAL_REVIEW.sql,Create_Table__T_NORM_CLINICAL_REVIEW.sql,ddl
11,ddl/Create_Table__T_NORM_DIAGNOSIS.sql,Create_Table__T_NORM_DIAGNOSIS.sql,ddl
12,ddl/Create_Table__T_NORM_ELIGIBILITY_REVIEW.sql,Create_Table__T_NORM_ELIGIBILITY_REVIEW.sql,ddl
13,ddl/Create_Table__T_NORM_INVOICE.sql,Create_Table__T_NORM_INVOICE.sql,ddl
14,ddl/Create_Table__T_NORM_PAYMENT.sql,Create_Table__T_NORM_PAYMENT.sql,ddl
15,ddl/Create_Table__T_NORM_POLICY.sql,Create_Table__T_NORM_POLICY.sql,ddl
16,ddl/Create_Table__T_NORM_POLICY_RIDER.sql,Create_Table__T_NORM_POLICY_RIDER.sql,ddl
17,ddl/Create_Table__T_NORM_REVIEW_CYCLE.sql,Create_Table__T_NORM_REVIEW_CYCLE.sql,ddl
18,ddl/Create_Table__T_NORM_REVIEW_CYCLE_METRIC.sql,Create_Table__T_NORM_REVIEW_CYCLE_METRIC.sql,ddl
19,ddl/Create_Table__T_NORM_REVIEW_CYCLE_REMEDIAT...,Create_Table__T_NORM_REVIEW_CYCLE_REMEDIATION.sql,ddl
20,ddl/Create_Table__T_RESOLVED_ADDRESS.sql,Create_Table__T_RESOLVED_ADDRESS.sql,ddl
21,ddl/Create_Table__T_RESOLVED_BANK_ACCOUNT.sql,Create_Table__T_RESOLVED_BANK_ACCOUNT.sql,ddl
22,ddl/Create_Table__T_RESOLVED_BUSINESS.sql,Create_Table__T_RESOLVED_BUSINESS.sql,ddl
23,ddl/Create_Table__T_RESOLVED_BUSINESS_ADDRESS_...,Create_Table__T_RESOLVED_BUSINESS_ADDRESS_CROS...,ddl
24,ddl/Create_Table__T_RESOLVED_BUSINESS_ELIGIBIL...,Create_Table__T_RESOLVED_BUSINESS_ELIGIBILITY_...,ddl
25,ddl/Create_Table__T_RESOLVED_BUSINESS_INVOICE_...,Create_Table__T_RESOLVED_BUSINESS_INVOICE_CROS...,ddl
26,ddl/Create_Table__T_RESOLVED_BUSINESS_PERSON_C...,Create_Table__T_RESOLVED_BUSINESS_PERSON_CROSS...,ddl
27,ddl/Create_Table__T_RESOLVED_CARE_SESSION_EVEN...,Create_Table__T_RESOLVED_CARE_SESSION_EVENT_GE...,ddl
28,ddl/Create_Table__T_RESOLVED_CARE_SESSION_GEOL...,Create_Table__T_RESOLVED_CARE_SESSION_GEOLOCAT...,ddl
29,ddl/Create_Table__T_RESOLVED_GEOLOCATION.sql,Create_Table__T_RESOLVED_GEOLOCATION.sql,ddl
30,ddl/Create_Table__T_RESOLVED_PAYMENT_BANK_ACCO...,Create_Table__T_RESOLVED_PAYMENT_BANK_ACCOUNT_...,ddl
31,ddl/Create_Table__T_RESOLVED_PERSON.sql,Create_Table__T_RESOLVED_PERSON.sql,ddl
32,ddl/Create_Table__T_RESOLVED_PERSON_ADDRESS_CR...,Create_Table__T_RESOLVED_PERSON_ADDRESS_CROSSW...,ddl
33,ddl/Create_Table__T_RESOLVED_PERSON_BANK_ACCOU...,Create_Table__T_RESOLVED_PERSON_BANK_ACCOUNT_C...,ddl
34,ddl/Create_Table__T_RESOLVED_PERSON_CARE_SESSI...,Create_Table__T_RESOLVED_PERSON_CARE_SESSION_C...,ddl
35,ddl/Create_Table__T_RESOLVED_PERSON_ELIGIBILIT...,Create_Table__T_RESOLVED_PERSON_ELIGIBILITY_RE...,ddl
36,ddl/Create_Table__T_RESOLVED_PERSON_INVOICE_CR...,Create_Table__T_RESOLVED_PERSON_INVOICE_CROSSW...,ddl
37,ddl/Create_Table__T_RESOLVED_PERSON_PERSON_CRO...,Create_Table__T_RESOLVED_PERSON_PERSON_CROSSWA...,ddl
38,ddl/Create_Table__T_RESOLVED_PERSON_POLICY_CRO...,Create_Table__T_RESOLVED_PERSON_POLICY_CROSSWA...,ddl
39,ddl/Create_View__V_RESOLVED_CARE_SESSION_GEOLO...,Create_View__V_RESOLVED_CARE_SESSION_GEOLOCATI...,ddl

## 5. All `.txt` and `.md` files

Documentation snippets (`docs__*.txt`), the graph model write-up (`GRAPH_DATA_MODEL.md`), and the high-level `readme.md` overview.

In [21]:
text_like = df[df["extension"].isin([".txt", ".md"])].copy()
text_like = text_like.sort_values("relative_path")
display(text_like[["relative_path", "file_name", "top_level_group"]])

,relative_path,file_name,top_level_group
41,documentation/docs__COG_impairment.txt,docs__COG_impairment.txt,documentation
42,documentation/docs__DMB.txt,docs__DMB.txt,documentation
43,documentation/docs__HIPAA.txt,docs__HIPAA.txt,documentation
44,documentation/docs__INVESTIGAI_ICP_CAREGIVER_A...,docs__INVESTIGAI_ICP_CAREGIVER_APP_SESSIONS.txt,documentation
45,documentation/docs__POA.txt,docs__POA.txt,documentation
46,documentation/docs__T_NORM_CARE_SESSION.txt,docs__T_NORM_CARE_SESSION.txt,documentation
47,documentation/docs__T_NORM_CARE_SESSION_EVENT.txt,docs__T_NORM_CARE_SESSION_EVENT.txt,documentation
48,documentation/docs__T_NORM_CLAIM.txt,docs__T_NORM_CLAIM.txt,documentation
49,documentation/docs__T_NORM_CLAIM_ELIGIBILITY_R...,docs__T_NORM_CLAIM_ELIGIBILITY_REVIEW_CROSSWAL...,documentation
50,documentation/docs__T_NORM_CLINICAL_REVIEW.txt,docs__T_NORM_CLINICAL_REVIEW.txt,documentation
51,documentation/docs__T_NORM_DIAGNOSIS.txt,docs__T_NORM_DIAGNOSIS.txt,documentation
52,documentation/docs__T_NORM_ELIGIBILITY_REVIEW.txt,docs__T_NORM_ELIGIBILITY_REVIEW.txt,documentation
53,documentation/docs__T_NORM_INVOICE.txt,docs__T_NORM_INVOICE.txt,documentation
54,documentation/docs__T_NORM_POLICY.txt,docs__T_NORM_POLICY.txt,documentation
55,documentation/docs__T_RESOLVED_ADDRESS.txt,docs__T_RESOLVED_ADDRESS.txt,documentation
56,documentation/docs__T_RESOLVED_BUSINESS.txt,docs__T_RESOLVED_BUSINESS.txt,documentation
57,documentation/docs__T_RESOLVED_BUSINESS_ELIGIB...,docs__T_RESOLVED_BUSINESS_ELIGIBILITY_REVIEW_C...,documentation
58,documentation/docs__T_RESOLVED_BUSINESS_INVOIC...,docs__T_RESOLVED_BUSINESS_INVOICE_CROSSWALK.txt,documentation
59,documentation/docs__T_RESOLVED_BUSINESS_PERSON...,docs__T_RESOLVED_BUSINESS_PERSON_CROSSWALK.txt,documentation
60,documentation/docs__T_RESOLVED_CARE_SESSION_GE...,docs__T_RESOLVED_CARE_SESSION_GEOLOCATION_CROS...,documentation
61,documentation/docs__T_RESOLVED_GEOLOCATION.txt,docs__T_RESOLVED_GEOLOCATION.txt,documentation
62,documentation/docs__T_RESOLVED_PERSON.txt,docs__T_RESOLVED_PERSON.txt,documentation
63,documentation/docs__T_RESOLVED_PERSON_ADDRESS_...,docs__T_RESOLVED_PERSON_ADDRESS_CROSSWALK.txt,documentation
64,documentation/docs__T_RESOLVED_PERSON_CARE_SES...,docs__T_RESOLVED_PERSON_CARE_SESSION_CROSSWALK...,documentation
65,documentation/docs__T_RESOLVED_PERSON_ELIGIBIL...,docs__T_RESOLVED_PERSON_ELIGIBILITY_REVIEW_CRO...,documentation
66,documentation/docs__T_RESOLVED_PERSON_INVOICE_...,docs__T_RESOLVED_PERSON_INVOICE_CROSSWALK.txt,documentation
67,documentation/docs__T_RESOLVED_PERSON_PERSON_C...,docs__T_RESOLVED_PERSON_PERSON_CROSSWALK.txt,documentation
68,documentation/docs__T_RESOLVED_PERSON_POLICY_C...,docs__T_RESOLVED_PERSON_POLICY_CROSSWALK.txt,documentation
69,documentation/docs__care_session_listings.txt,docs__care_session_listings.txt,documentation
70,documentation/docs__clinical_review_listings.txt,docs__clinical_review_listings.txt,documentation
71,documentation/docs__deceased.txt,docs__deceased.txt,documentation
72,documentation/docs__eligibility_review_query.txt,docs__eligibility_review_query.txt,documentation
73,documentation/docs__geolocation_enabled.txt,docs__geolocation_enabled.txt,documentation
74,documentation/docs__hourly_rate.txt,docs__hourly_rate.txt,documentation
75,documentation/docs__icp_no_breaks.txt,docs__icp_no_breaks.txt,documentation
76,documentation/docs__icp_shared_device_ids.txt,docs__icp_shared_device_ids.txt,documentation
77,documentation/docs__invoice_listings.txt,docs__invoice_listings.txt,documentation
78,documentation/docs__multi_icp_overlap.txt,docs__multi_icp_overlap.txt,documentation
79,documentation/docs__no_touch.txt,docs__no_touch.txt,documentation
80,documentation/docs__payments.txt,docs__payments.txt,documentation
81,documentation/docs__policyholder_query.txt,docs__policyholder_query.txt,documentation
82,documentation/docs__provider_query.txt,docs__provider_query.txt,documentation
83,documentation/docs__review_cycles.txt,docs__review_cycles.txt,documentation
84,documentation/docs__session_address_distance.txt,docs__session_address_distance.txt,documentation
85,documentation/docs__spouses.txt,docs__spouses.txt,documentation
86,documentation/docs__start_of_care.txt,docs__start_of_care.txt,documentation
87,documentation/docs__writing_agent.txt,docs__writing_agent.txt,documentation
89,graph/GRAPH_DATA_MODEL.md,GRAPH_DATA_MODEL.md,graph
90,readme.md,readme.md,other